#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLNhanVien")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttNhanVien(tNhanVien instance);
    partial void UpdatetNhanVien(tNhanVien instance);
    partial void DeletetNhanVien(tNhanVien instance);
    partial void InserttHangHoa(tHangHoa instance);
    partial void UpdatetHangHoa(tHangHoa instance);
    partial void DeletetHangHoa(tHangHoa instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLNhanVienConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tNhanVien> tNhanViens
		{
			get
			{
				return this.GetTable<tNhanVien>();
			}
		}
		
		public System.Data.Linq.Table<tHangHoa> tHangHoas
		{
			get
			{
				return this.GetTable<tHangHoa>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tNhanVien")]
	public partial class tNhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _HO;
		
		private string _TEN;
		
		private bool _PHAI;
		
		private System.Nullable<System.DateTime> _NTNS;
		
		private System.Nullable<System.DateTime> _NgayBD;
		
		private string _MaPB;
		
		private System.Data.Linq.Binary _HINH;
		
		private string _GHICHU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnHOChanging(string value);
    partial void OnHOChanged();
    partial void OnTENChanging(string value);
    partial void OnTENChanged();
    partial void OnPHAIChanging(bool value);
    partial void OnPHAIChanged();
    partial void OnNTNSChanging(System.Nullable<System.DateTime> value);
    partial void OnNTNSChanged();
    partial void OnNgayBDChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBDChanged();
    partial void OnMaPBChanging(string value);
    partial void OnMaPBChanged();
    partial void OnHINHChanging(System.Data.Linq.Binary value);
    partial void OnHINHChanged();
    partial void OnGHICHUChanging(string value);
    partial void OnGHICHUChanged();
    #endregion
		
		public tNhanVien()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NVarChar(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HO", DbType="NVarChar(15)")]
		public string HO
		{
			get
			{
				return this._HO;
			}
			set
			{
				if ((this._HO != value))
				{
					this.OnHOChanging(value);
					this.SendPropertyChanging();
					this._HO = value;
					this.SendPropertyChanged("HO");
					this.OnHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN", DbType="NVarChar(7)")]
		public string TEN
		{
			get
			{
				return this._TEN;
			}
			set
			{
				if ((this._TEN != value))
				{
					this.OnTENChanging(value);
					this.SendPropertyChanging();
					this._TEN = value;
					this.SendPropertyChanged("TEN");
					this.OnTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHAI", DbType="Bit NOT NULL")]
		public bool PHAI
		{
			get
			{
				return this._PHAI;
			}
			set
			{
				if ((this._PHAI != value))
				{
					this.OnPHAIChanging(value);
					this.SendPropertyChanging();
					this._PHAI = value;
					this.SendPropertyChanged("PHAI");
					this.OnPHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NTNS", DbType="DateTime")]
		public System.Nullable<System.DateTime> NTNS
		{
			get
			{
				return this._NTNS;
			}
			set
			{
				if ((this._NTNS != value))
				{
					this.OnNTNSChanging(value);
					this.SendPropertyChanging();
					this._NTNS = value;
					this.SendPropertyChanged("NTNS");
					this.OnNTNSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBD", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayBD
		{
			get
			{
				return this._NgayBD;
			}
			set
			{
				if ((this._NgayBD != value))
				{
					this.OnNgayBDChanging(value);
					this.SendPropertyChanging();
					this._NgayBD = value;
					this.SendPropertyChanged("NgayBD");
					this.OnNgayBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPB", DbType="NVarChar(2)")]
		public string MaPB
		{
			get
			{
				return this._MaPB;
			}
			set
			{
				if ((this._MaPB != value))
				{
					this.OnMaPBChanging(value);
					this.SendPropertyChanging();
					this._MaPB = value;
					this.SendPropertyChanged("MaPB");
					this.OnMaPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINH", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary HINH
		{
			get
			{
				return this._HINH;
			}
			set
			{
				if ((this._HINH != value))
				{
					this.OnHINHChanging(value);
					this.SendPropertyChanging();
					this._HINH = value;
					this.SendPropertyChanged("HINH");
					this.OnHINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHICHU", DbType="NVarChar(MAX)")]
		public string GHICHU
		{
			get
			{
				return this._GHICHU;
			}
			set
			{
				if ((this._GHICHU != value))
				{
					this.OnGHICHUChanging(value);
					this.SendPropertyChanging();
					this._GHICHU = value;
					this.SendPropertyChanged("GHICHU");
					this.OnGHICHUChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tHangHoa")]
	public partial class tHangHoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHang;
		
		private string _TenHang;
		
		private System.Nullable<int> _MaLoai;
		
		private System.Nullable<int> _MaKichThuoc;
		
		private System.Nullable<int> _MaCongDung;
		
		private System.Nullable<int> _MaLoaiMen;
		
		private System.Nullable<int> _MaHinhKhoi;
		
		private System.Nullable<int> _MaHoaVan;
		
		private System.Nullable<int> _MaMau;
		
		private System.Nullable<int> _MaNuoc;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<decimal> _DonGiaNhap;
		
		private System.Nullable<decimal> _DonGiaBan;
		
		private System.Nullable<int> _ThoiGianBaoHanh;
		
		private string _Anh;
		
		private string _GhiChu;
		
		private System.Nullable<bool> _Deleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHangChanging(int value);
    partial void OnMaHangChanged();
    partial void OnTenHangChanging(string value);
    partial void OnTenHangChanged();
    partial void OnMaLoaiChanging(System.Nullable<int> value);
    partial void OnMaLoaiChanged();
    partial void OnMaKichThuocChanging(System.Nullable<int> value);
    partial void OnMaKichThuocChanged();
    partial void OnMaCongDungChanging(System.Nullable<int> value);
    partial void OnMaCongDungChanged();
    partial void OnMaLoaiMenChanging(System.Nullable<int> value);
    partial void OnMaLoaiMenChanged();
    partial void OnMaHinhKhoiChanging(System.Nullable<int> value);
    partial void OnMaHinhKhoiChanged();
    partial void OnMaHoaVanChanging(System.Nullable<int> value);
    partial void OnMaHoaVanChanged();
    partial void OnMaMauChanging(System.Nullable<int> value);
    partial void OnMaMauChanged();
    partial void OnMaNuocChanging(System.Nullable<int> value);
    partial void OnMaNuocChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnDonGiaNhapChanging(System.Nullable<decimal> value);
    partial void OnDonGiaNhapChanged();
    partial void OnDonGiaBanChanging(System.Nullable<decimal> value);
    partial void OnDonGiaBanChanged();
    partial void OnThoiGianBaoHanhChanging(System.Nullable<int> value);
    partial void OnThoiGianBaoHanhChanged();
    partial void OnAnhChanging(string value);
    partial void OnAnhChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnDeletedChanging(System.Nullable<bool> value);
    partial void OnDeletedChanged();
    #endregion
		
		public tHangHoa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaHang
		{
			get
			{
				return this._MaHang;
			}
			set
			{
				if ((this._MaHang != value))
				{
					this.OnMaHangChanging(value);
					this.SendPropertyChanging();
					this._MaHang = value;
					this.SendPropertyChanged("MaHang");
					this.OnMaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenHang
		{
			get
			{
				return this._TenHang;
			}
			set
			{
				if ((this._TenHang != value))
				{
					this.OnTenHangChanging(value);
					this.SendPropertyChanging();
					this._TenHang = value;
					this.SendPropertyChanged("TenHang");
					this.OnTenHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="Int")]
		public System.Nullable<int> MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKichThuoc", DbType="Int")]
		public System.Nullable<int> MaKichThuoc
		{
			get
			{
				return this._MaKichThuoc;
			}
			set
			{
				if ((this._MaKichThuoc != value))
				{
					this.OnMaKichThuocChanging(value);
					this.SendPropertyChanging();
					this._MaKichThuoc = value;
					this.SendPropertyChanged("MaKichThuoc");
					this.OnMaKichThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCongDung", DbType="Int")]
		public System.Nullable<int> MaCongDung
		{
			get
			{
				return this._MaCongDung;
			}
			set
			{
				if ((this._MaCongDung != value))
				{
					this.OnMaCongDungChanging(value);
					this.SendPropertyChanging();
					this._MaCongDung = value;
					this.SendPropertyChanged("MaCongDung");
					this.OnMaCongDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiMen", DbType="Int")]
		public System.Nullable<int> MaLoaiMen
		{
			get
			{
				return this._MaLoaiMen;
			}
			set
			{
				if ((this._MaLoaiMen != value))
				{
					this.OnMaLoaiMenChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiMen = value;
					this.SendPropertyChanged("MaLoaiMen");
					this.OnMaLoaiMenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHinhKhoi", DbType="Int")]
		public System.Nullable<int> MaHinhKhoi
		{
			get
			{
				return this._MaHinhKhoi;
			}
			set
			{
				if ((this._MaHinhKhoi != value))
				{
					this.OnMaHinhKhoiChanging(value);
					this.SendPropertyChanging();
					this._MaHinhKhoi = value;
					this.SendPropertyChanged("MaHinhKhoi");
					this.OnMaHinhKhoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaVan", DbType="Int")]
		public System.Nullable<int> MaHoaVan
		{
			get
			{
				return this._MaHoaVan;
			}
			set
			{
				if ((this._MaHoaVan != value))
				{
					this.OnMaHoaVanChanging(value);
					this.SendPropertyChanging();
					this._MaHoaVan = value;
					this.SendPropertyChanged("MaHoaVan");
					this.OnMaHoaVanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMau", DbType="Int")]
		public System.Nullable<int> MaMau
		{
			get
			{
				return this._MaMau;
			}
			set
			{
				if ((this._MaMau != value))
				{
					this.OnMaMauChanging(value);
					this.SendPropertyChanging();
					this._MaMau = value;
					this.SendPropertyChanged("MaMau");
					this.OnMaMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNuoc", DbType="Int")]
		public System.Nullable<int> MaNuoc
		{
			get
			{
				return this._MaNuoc;
			}
			set
			{
				if ((this._MaNuoc != value))
				{
					this.OnMaNuocChanging(value);
					this.SendPropertyChanging();
					this._MaNuoc = value;
					this.SendPropertyChanged("MaNuoc");
					this.OnMaNuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGiaNhap", DbType="Money")]
		public System.Nullable<decimal> DonGiaNhap
		{
			get
			{
				return this._DonGiaNhap;
			}
			set
			{
				if ((this._DonGiaNhap != value))
				{
					this.OnDonGiaNhapChanging(value);
					this.SendPropertyChanging();
					this._DonGiaNhap = value;
					this.SendPropertyChanged("DonGiaNhap");
					this.OnDonGiaNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGiaBan", DbType="Money")]
		public System.Nullable<decimal> DonGiaBan
		{
			get
			{
				return this._DonGiaBan;
			}
			set
			{
				if ((this._DonGiaBan != value))
				{
					this.OnDonGiaBanChanging(value);
					this.SendPropertyChanging();
					this._DonGiaBan = value;
					this.SendPropertyChanged("DonGiaBan");
					this.OnDonGiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianBaoHanh", DbType="Int")]
		public System.Nullable<int> ThoiGianBaoHanh
		{
			get
			{
				return this._ThoiGianBaoHanh;
			}
			set
			{
				if ((this._ThoiGianBaoHanh != value))
				{
					this.OnThoiGianBaoHanhChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianBaoHanh = value;
					this.SendPropertyChanged("ThoiGianBaoHanh");
					this.OnThoiGianBaoHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Anh
		{
			get
			{
				return this._Anh;
			}
			set
			{
				if ((this._Anh != value))
				{
					this.OnAnhChanging(value);
					this.SendPropertyChanging();
					this._Anh = value;
					this.SendPropertyChanged("Anh");
					this.OnAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Bit")]
		public System.Nullable<bool> Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
